/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description The process is running. Says nothing about its dependencies.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description The process can serve traffic, including reaching its database.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a one-time code by SMS
         * @description Never reveals whether an account exists; users are created on first
         *     successful verification. Rate limited per phone and per client IP.
         */
        post: operations["requestOTP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a code for a session */
        post: operations["verifyOTP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token
         * @description Every refresh issues a new refresh token and retires the old one.
         *     Replaying a retired token after the grace window revokes the whole
         *     session family, on the assumption that it was stolen.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a session family */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /** Close account and remove profile data */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @constant */
                        confirmation: "DELETE";
                    };
                };
            };
            responses: {
                /** @description Success */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not permitted */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Resolve outstanding responsibilities first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid input */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update the signed-in user's display name
         * @description Names are shown to the other party before booking, so contact details are refused.
         */
        patch: operations["patchMe"];
        trace?: never;
    };
    "/v1/auth/external": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a verified provider identity for a Findaspace session
         * @description Only the trusted web backend may call this endpoint. Provider issuer, audience, signature, expiry and nonce are verified by the API.
         */
        post: operations["externalLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/sign-in-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List connected external sign-in methods */
        get: operations["signInMethods"];
        put?: never;
        /** Connect a provider to the recently authenticated account */
        post: operations["linkSignInMethod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify and connect a phone to the recently authenticated account */
        post: operations["linkPhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search published listings
         * @description Keyset paginated. Pass next_cursor back as cursor to continue; a new
         *     filter means starting again without one.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/listings/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A published listing, as any visitor may see it */
        get: operations["getListing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/listings/{slug}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready photos, in the host's order */
        get: operations["getListingMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/listings/{slug}/walks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Walking times to the nearest landmarks */
        get: operations["getListingWalks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/listings/{slug}/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The walkthrough video, if one is ready */
        get: operations["getListingVideo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/listings/{slug}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Published guest reviews */
        get: operations["getListingReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/listings/{slug}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Price a stay or a lease
         * @description Term listings need starts_on and months. Nightly listings need check_in
         *     and check_out. Dates are YYYY-MM-DD.
         */
        get: operations["getListingQuote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/space-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every space type, its fields and their labels
         * @description The one source of truth for attribute labels. Clients never duplicate them.
         */
        get: operations["getSpaceTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in host's own listings, every status */
        get: operations["listOwnListings"];
        put?: never;
        /**
         * Create a draft listing
         * @description Grants the host role on first use. The listing starts as a draft.
         */
        post: operations["createListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the caller’s own listing */
        get: operations["getOwnListing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a listing the caller owns */
        patch: operations["patchListing"];
        trace?: never;
    };
    "/v1/spaces/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a draft for review
         * @description Needs at least one ready photo, a locality and a price. An admin then publishes it.
         */
        post: operations["submitListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The listing's ready photos */
        get: operations["listOwnMedia"];
        put?: never;
        /** Reserve a photo slot and get a presigned upload URL */
        post: operations["requestUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{id}/media/{mediaId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tell the API an upload finished
         * @description Verifies the object exists, then queues processing. Returns while the photo is still pending.
         */
        post: operations["confirmUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/listings/{slug}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nightly availability and prices */
        get: operations["getListingCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's bookings as a guest, or as a host with role=host */
        get: operations["listBookings"];
        put?: never;
        /**
         * Hold dates, or request a lease
         * @description Nightly bookings are held for payment. Term bookings are requests the
         *     host approves before anything is paid. Priced on the server, always.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One booking, for its guest or host */
        get: operations["getBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start, or resume, payment for a payable booking
         * @description Payable means held for nightly, approved for term. Returns the open attempt if one exists.
         */
        post: operations["payBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The host approves a lease request, which starts the guest's payment window */
        post: operations["approveBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The host declines a request */
        post: operations["declineBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payouts/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The host's payout account, if one is saved */
        get: operations["getPayoutAccount"];
        /** Save the host's mobile money payout account */
        put: operations["savePayoutAccount"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payouts/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the host has earned, held and can withdraw */
        get: operations["getBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The host's payouts, newest first */
        get: operations["listPayouts"];
        put?: never;
        /** Withdraw to the saved account */
        post: operations["requestPayout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Message a listing's host; opens the conversation or continues it */
        post: operations["messageHost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's conversations, most recent first */
        get: operations["listThreads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A page of messages, newest first */
        get: operations["listMessages"];
        put?: never;
        /** Reply in a conversation */
        post: operations["replyThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a conversation read up to now */
        post: operations["readThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's notifications, newest first, with the unread count */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark one notification read */
        post: operations["readNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark every notification read */
        post: operations["readAllNotifications"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{id}/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The owner's name and phone number, for a signed-in renter
         * @description Only published listings. Every reveal is recorded against the viewer's
         *     verified account, and each account may reveal a limited number of
         *     numbers a day, so the directory of hosts cannot be scraped.
         */
        get: operations["revealContact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw a listing owned by the caller */
        post: operations["withdrawListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a listing owned by the caller */
        post: operations["archiveListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{id}/media/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set ready photos in the exact supplied order; first is cover */
        put: operations["reorderMedia"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{id}/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a photo; keep at least one ready photo on a published listing */
        delete: operations["deleteMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spaces/{id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a published listing */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        reason: "suspected_scam" | "unavailable" | "incorrect_details" | "abuse" | "other";
                        details?: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            status: string;
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not permitted */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Resolve outstanding responsibilities first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid input */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{id}/safety": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Communication boundaries for a participant */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunicationBoundary"];
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not permitted */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Resolve outstanding responsibilities first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid input */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{id}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block messages and new contact reveals from this person */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not permitted */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Resolve outstanding responsibilities first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid input */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Remove your own block */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not permitted */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Resolve outstanding responsibilities first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid input */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open reports; administrator or support only */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            reports: components["schemas"]["ListingReport"][];
                        };
                    };
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not permitted */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Resolve outstanding responsibilities first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid input */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/reports/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve or dismiss a report */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "resolved" | "dismissed";
                        note?: string;
                        /** @default false */
                        withdraw_listing?: boolean;
                    };
                };
            };
            responses: {
                /** @description Success */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not signed in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not permitted */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Resolve outstanding responsibilities first */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid input */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            type?: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description Matches request_id in the server logs. */
            trace_id?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            field: string;
            code: string;
            detail?: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            version?: string;
        };
        Readiness: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            checks?: {
                [key: string]: string;
            };
        };
        ExternalLogin: {
            /** @enum {string} */
            provider: "google" | "microsoft" | "apple";
            id_token: string;
            nonce: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** @description Verified E.164 contact number, or an empty string when no phone is connected. */
            phone: string;
            phone_verified?: boolean;
            display_name: string;
            roles: ("guest" | "host" | "admin" | "support")[];
            /** Format: date-time */
            created_at: string;
        };
        TokenResponse: {
            user: components["schemas"]["User"];
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** Format: date-time */
            expires_at: string;
            refresh_token: string;
            /** Format: date-time */
            refresh_expires_at: string;
        };
        OTPSent: {
            /** @description Masked. The full number is never echoed back. */
            phone: string;
            /** Format: date-time */
            expires_at: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        SearchResult: {
            slug: string;
            title: string;
            /** @enum {string} */
            space_type: "room" | "self_contained" | "chamber_and_hall" | "apartment" | "house" | "boys_quarters" | "hostel_bed" | "shop" | "office" | "warehouse" | "event_space" | "land" | "parking" | "studio" | "football_pitch" | "sports_court" | "sports_facility";
            /** @enum {string} */
            rental_mode: "nightly" | "term" | "flexible";
            /**
             * Format: int64
             * @description Minor units. 130000 is GHS 1,300.
             */
            price_minor: number;
            currency: string;
            /** @enum {string} */
            price_period: "night" | "week" | "month" | "year" | "hour" | "day" | "semester" | "academic_year";
            locality: string;
            /** @description The nearest routed landmark. Absent until the listing has been routed. */
            landmark_name?: string;
            /** @description Walking time to landmark_name. Absent until routed. */
            walk_minutes?: number;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            photo_count: number;
            /** @description The card-sized rendition when one exists, otherwise the full image. */
            cover_url?: string;
            /** Format: double */
            rating?: number;
            review_count: number;
            distance_m?: number;
        };
        SearchPage: {
            results: components["schemas"]["SearchResult"][];
            /** @description Opaque. Present only when another page exists. */
            next_cursor?: string;
        };
        PublicLocation: {
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            locality: string;
            region: string;
            country: string;
            landmark?: string;
            /** @description Always true. The point is snapped to a grid about 550m across until booking. */
            approximate: boolean;
        };
        PublicListing: {
            /**
             * Format: uuid
             * @description The listing's id. Booking and messaging are addressed by it.
             */
            id: string;
            slug: string;
            space_type: components["schemas"]["SearchResult"]["space_type"];
            /** @enum {string} */
            rental_mode: "nightly" | "term" | "flexible";
            title: string;
            description: string;
            /** Format: int64 */
            base_price_minor: number;
            currency: string;
            /** @enum {string} */
            price_period: "night" | "week" | "month" | "year" | "hour" | "day" | "semester" | "academic_year";
            /** Format: int64 */
            deposit_minor: number;
            advance_months: number;
            max_occupancy: number;
            location: components["schemas"]["PublicLocation"];
            amenities: string[];
            attributes: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            published_at?: string | null;
        };
        Media: {
            id: string;
            /** @description The full image, for the listing page. */
            url: string;
            /**
             * @description A small JPEG rendition, around 60KB. Absent for photos uploaded
             *     before renditions existed.
             */
            card_url?: string;
            content_type?: string;
            width: number;
            height: number;
            byte_size?: number;
            position: number;
            status?: string;
        };
        Walk: {
            name: string;
            kind: string;
            locality?: string;
            minutes: number;
            metres: number;
        };
        Video: {
            /** @enum {string} */
            status: "pending" | "processing" | "ready" | "failed";
            video_url?: string;
            poster_url?: string;
            duration_seconds?: number;
            width?: number;
            height?: number;
        };
        QuoteLine: {
            code: string;
            label: string;
            /** Format: int64 */
            amount_minor: number;
        };
        Quote: {
            /** @enum {string} */
            mode: "nightly" | "term" | "flexible";
            currency: string;
            /** Format: date-time */
            check_in?: string;
            /** Format: date-time */
            check_out?: string;
            nights?: number;
            months?: number;
            lines: components["schemas"]["QuoteLine"][];
            /** Format: int64 */
            subtotal_minor: number;
            /** Format: int64 */
            discount_minor: number;
            /** Format: int64 */
            fees_minor: number;
            /** Format: int64 */
            total_minor: number;
            /**
             * Format: int64
             * @description What leaves the renter's account today, including rent in advance and deposit.
             */
            due_now_minor: number;
        };
        ReviewSummary: {
            count: number;
            /** Format: double */
            average: number;
        };
        FieldSchema: {
            key: string;
            label: string;
            /** @enum {string} */
            kind: "int" | "float" | "bool" | "enum" | "string";
            weight?: number;
            unit?: string;
            options?: string[];
        };
        TypeSchema: {
            type: string;
            label: string;
            modes?: string[];
            fields: components["schemas"]["FieldSchema"][];
            price_periods?: ("night" | "week" | "month" | "year" | "hour" | "day" | "semester" | "academic_year")[];
        };
        HostLocation: {
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            locality: string;
            region?: string;
            country?: string;
            landmark?: string;
            digital_address?: string;
        };
        /** @description The host's own view. Carries the exact location; never served publicly. */
        HostListing: {
            /** Format: uuid */
            id: string;
            slug: string;
            space_type: components["schemas"]["SearchResult"]["space_type"];
            /** @enum {string} */
            rental_mode: "nightly" | "term" | "flexible";
            /** @enum {string} */
            status: "draft" | "in_review" | "published" | "suspended" | "archived";
            title: string;
            description?: string;
            /** Format: int64 */
            base_price_minor: number;
            currency: string;
            /** @enum {string} */
            price_period: "night" | "week" | "month" | "year" | "hour" | "day" | "semester" | "academic_year";
            /** Format: int64 */
            deposit_minor?: number;
            advance_months?: number;
            max_occupancy?: number;
            location: components["schemas"]["HostLocation"];
            amenities?: string[];
            attributes: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            published_at?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: uuid */
            host_id?: string;
        };
        CreateListing: {
            space_type: components["schemas"]["SearchResult"]["space_type"];
            /** @enum {string} */
            rental_mode: "nightly" | "term" | "flexible";
            title: string;
            description?: string;
            /** Format: int64 */
            base_price_minor: number;
            currency?: string;
            /** @enum {string} */
            price_period: "night" | "week" | "month" | "year" | "hour" | "day" | "semester" | "academic_year";
            /** Format: int64 */
            deposit_minor?: number;
            advance_months?: number;
            max_occupancy: number;
            location: {
                /** Format: double */
                latitude: number;
                /** Format: double */
                longitude: number;
                locality: string;
                region?: string;
                country?: string;
                landmark?: string;
                digital_address?: string;
            };
            amenities?: string[];
            attributes?: {
                [key: string]: unknown;
            };
        };
        UploadTicket: {
            media: components["schemas"]["Media"];
            upload_url: string;
            /** Format: date-time */
            expires_at?: string;
            /** Format: int64 */
            max_bytes?: number;
            method?: string;
            headers: {
                [key: string]: string;
            };
        };
        Booking: {
            /** Format: uuid */
            id: string;
            reference: string;
            /** Format: uuid */
            space_id: string;
            /** @description Shown only to the host, so they know who is asking. */
            guest?: {
                display_name: string;
                /** Format: date-time */
                member_since: string;
                phone_verified: boolean;
            };
            /**
             * @description The exact address. The host always sees it; the guest only once the
             *     booking is paid (confirmed, active or completed).
             */
            location?: {
                /** Format: double */
                latitude: number;
                /** Format: double */
                longitude: number;
                locality: string;
                landmark?: string;
                digital_address?: string;
            };
            /** @description The listing, for display. Absent if it could not be loaded. */
            space?: {
                slug: string;
                title: string;
            };
            /** @enum {string} */
            rental_mode: "nightly" | "term" | "flexible";
            /** @enum {string} */
            status: "held" | "approved" | "confirmed" | "active" | "completed" | "cancelled" | "declined" | "expired";
            /** Format: date */
            starts_on: string;
            /** Format: date */
            ends_on: string;
            nights?: number;
            months?: number;
            guests: number;
            currency: string;
            /** Format: int64 */
            total_minor: number;
            /** Format: int64 */
            due_now_minor: number;
            cancellation_policy?: string;
            /** Format: int64 */
            refund_minor?: number;
            /**
             * Format: date-time
             * @description While held, the deadline to pay (nightly) or for the host to respond
             *     (term). While approved, the deadline to pay.
             */
            hold_expires_at?: string;
            /** Format: date-time */
            created_at: string;
        };
        PaymentIntent: {
            payment_id?: string;
            reference: string;
            access_code?: string;
            authorization_url: string;
            /** Format: int64 */
            amount_minor: number;
            currency: string;
            status?: string;
        };
        Night: {
            /** Format: date-time */
            date: string;
            /** Format: int64 */
            price_minor: number;
            source?: string;
            available: boolean;
        };
        PayoutAccount: {
            id: string;
            channel: string;
            /** @description MTN, VOD (Telecel Cash) or ATL (AT Money). */
            bank_code: string;
            account_number: string;
            account_name: string;
            verified: boolean;
        };
        Balance: {
            currency: string;
            /** Format: int64 */
            total_minor: number;
            /** Format: int64 */
            available_minor: number;
            /**
             * Format: int64
             * @description Paid by guests and held until they move in.
             */
            pending_minor: number;
            /** Format: int64 */
            in_flight_minor: number;
            /** Format: int64 */
            withdrawable_minor: number;
        };
        Payout: {
            id: string;
            reference: string;
            status: string;
            currency: string;
            /** Format: int64 */
            amount_minor: number;
            failure_reason?: string;
            /** Format: date-time */
            settled_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Message: {
            id: string;
            sender_id: string;
            body: string;
            /** @description Contact details were removed because no booking is paid yet. */
            redacted: boolean;
            /** Format: date-time */
            created_at: string;
        };
        ThreadHeader: {
            id: string;
            /** @enum {string} */
            role: "guest" | "host";
            space?: {
                slug: string;
                title: string;
            };
            /** @description The other person in the conversation. */
            with?: {
                display_name: string;
            };
        };
        ThreadSummary: {
            id: string;
            space_id: string;
            /** @enum {string} */
            role: "guest" | "host";
            unread: boolean;
            /** Format: date-time */
            last_message_at?: string | null;
            /** @description A preview of the newest message, as stored, so already redacted. */
            last_message?: string;
            space?: {
                slug: string;
                title: string;
            };
            with?: {
                display_name: string;
            };
        };
        Notification: {
            id: string;
            event: string;
            title: string;
            body: string;
            data?: {
                [key: string]: unknown;
            };
            read: boolean;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Updates only drafts or listings in review. Editing returns the listing to draft; withdraw a published listing before editing. Attributes are a complete replacement document. */
        PatchListing: {
            /** @enum {string} */
            rental_mode?: "nightly" | "term" | "flexible";
            title?: string;
            description?: string;
            /** Format: int64 */
            base_price_minor?: number;
            /** @enum {string} */
            price_period?: "night" | "week" | "month" | "year" | "hour" | "day" | "semester" | "academic_year";
            /** Format: int64 */
            deposit_minor?: number;
            advance_months?: number;
            max_occupancy?: number;
            amenities?: string[];
            attributes?: {
                [key: string]: unknown;
            };
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            locality?: string;
            region?: string;
            landmark?: string;
            digital_address?: string;
        };
        ListingReport: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            space_id: string;
            reason: string;
            details: string;
            status: string;
            /** Format: date-time */
            created_at: string;
            title: string;
            slug: string;
        };
        CommunicationBoundary: {
            blocked: boolean;
            messaging_allowed: boolean;
        };
    };
    responses: {
        /** @description RFC 9457 problem document */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    requestOTP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Any common Ghanaian format; normalised to E.164. */
                    phone: string;
                };
            };
        };
        responses: {
            /** @description Code sent */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OTPSent"];
                };
            };
            400: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    verifyOTP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    phone: string;
                    code: string;
                };
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    patchMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    display_name: string;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    externalLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalLogin"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    signInMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connected methods */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        methods: ("google" | "microsoft" | "apple")[];
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    linkSignInMethod: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalLogin"];
            };
        };
        responses: {
            /** @description Connected and session renewed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    linkPhone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    phone: string;
                    code: string;
                };
            };
        };
        responses: {
            /** @description Phone connected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    search: {
        parameters: {
            query?: {
                q?: string;
                /**
                 * @description One space type, or several joined by commas. Never repeated: the
                 *     API reads this parameter once, so type=a&type=b keeps only a.
                 */
                type?: string;
                mode?: "nightly" | "term" | "flexible";
                /** @description Minor units. */
                max_price?: number;
                sort?: "relevance" | "price_asc" | "price_desc" | "distance" | "newest";
                cursor?: string;
                limit?: number;
                /** @description Filter to the same advertised rate period before comparing prices. */
                price_period?: "night" | "week" | "month" | "year" | "hour" | "day" | "semester" | "academic_year";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    getListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicListing"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getListingMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Photos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        media: components["schemas"]["Media"][];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getListingWalks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to three walks, nearest first. Empty until the listing is routed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        walks: components["schemas"]["Walk"][];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getListingVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A ready walkthrough */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            /** @description No ready walkthrough. Not an error for a visitor; just no badge. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getListingReviews: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary and the most recent reviews */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        summary: components["schemas"]["ReviewSummary"];
                        reviews: {
                            rating: number;
                            body: string;
                            /** Format: date-time */
                            published_at?: string;
                        }[];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getListingQuote: {
        parameters: {
            query?: {
                starts_on?: string;
                months?: number;
                check_in?: string;
                check_out?: string;
                guests?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The quote */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"];
                };
            };
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getSpaceTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schemas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        types: components["schemas"]["TypeSchema"][];
                    };
                };
            };
        };
    };
    listOwnListings: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listings, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        spaces: components["schemas"]["HostListing"][];
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    createListing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateListing"];
            };
        };
        responses: {
            /** @description Created as a draft */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostListing"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getOwnListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostListing"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    patchListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchListing"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostListing"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    submitListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Now in review */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostListing"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listOwnMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready photos only; ones still processing are not listed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        media: components["schemas"]["Media"][];
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    requestUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    content_type: "image/jpeg" | "image/png";
                };
            };
        };
        responses: {
            /** @description Upload the bytes to upload_url with exactly these headers */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadTicket"];
                };
            };
            401: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    confirmUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                mediaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            401: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getListingCalendar: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per night */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        currency: string;
                        nights: components["schemas"]["Night"][];
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listBookings: {
        parameters: {
            query?: {
                role?: "guest" | "host";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookings, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        bookings: components["schemas"]["Booking"][];
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: {
                /** @description Retrying with the same key returns the original booking instead of a second one. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    space_id: string;
                    /** Format: date */
                    check_in?: string;
                    /** Format: date */
                    check_out?: string;
                    /** Format: date */
                    starts_on?: string;
                    months?: number;
                    guests?: number;
                };
            };
        };
        responses: {
            /** @description Held */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The booking */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    payBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Send the guest to authorization_url */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentIntent"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    approveBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    declineBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Declined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getPayoutAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutAccount"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    savePayoutAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    channel?: string;
                    /** @enum {string} */
                    bank_code: "MTN" | "VOD" | "ATL";
                    account_number: string;
                    account_name: string;
                };
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutAccount"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The balance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Balance"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    listPayouts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payouts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payouts: components["schemas"]["Payout"][];
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    requestPayout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    amount_minor: number;
                };
            };
        };
        responses: {
            /** @description Accepted; the transfer settles asynchronously */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payout"];
                };
            };
            401: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    messageHost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    body: string;
                };
            };
        };
        responses: {
            /** @description Sent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        thread_id: string;
                        message: components["schemas"]["Message"];
                    };
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listThreads: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        threads: components["schemas"]["ThreadSummary"][];
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                before?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        thread?: components["schemas"]["ThreadHeader"];
                        messages: components["schemas"]["Message"][];
                        next_before?: string;
                    };
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    replyThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    body: string;
                };
            };
        };
        responses: {
            /** @description Sent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    readThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                before?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        notifications: components["schemas"]["Notification"][];
                        unread: number;
                        next_before?: string;
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    readNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    readAllNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        marked?: number;
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    revealContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The owner's contact */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        display_name: string;
                        /** @description Verified E.164 contact number, or an empty string when no phone is connected. */
                        phone: string;
                    };
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            phone_verified: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    withdrawListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostListing"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    archiveListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostListing"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    reorderMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ids: string[];
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        media: components["schemas"]["Media"][];
                    };
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    deleteMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                mediaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
}
